version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: goa_user
      POSTGRES_PASSWORD: goa_password
      POSTGRES_DB: goa_db
    ports:
      - "5432:5432"
    volumes:
      - goa_postgres_data:/var/lib/postgresql/data

volumes:
  goa_postgres_data:
